### ISSUE TITLE
Webページの作成

### ISSUE THREAD

**Issue by takanakahiko** [vlueprint/vlueprint#12]
Webページが必要です

- vlueprint.org : トップページ
- vlueprint.org/sparql : https://foobar-moezsesd6a-an.a.run.app/sparql/ をプロキシ
- vlueprint.org/rdfs : 各URIに付随するページ

セキュリティの懸念点はないので， SSR で実装していきたいです．

[PrismDB](https://prismdb.takanakahiko.me/) の場合は Nuxt.js で作りましたが，特にこだわりはないです． Next.js ，あるいはもっと他のフレームワークでも大丈夫です．

ここらへんの実装に興味がある人に意見を伺いたいです．

**Comment by takanakahiko** [comment]
Nuxt.js か Next.js かなあという気分です．
どちらの方が貢献してもらいやすいだろうか？

(私個人の習熟度としては Nuxt.js が高く，現状レビュワーが私一人であれば Nuxt.js を採用したほうが品質が保てて良いかなという気がします)

**Comment by takanakahiko** [comment]
Web ページガンガン貢献するぞという人の意見を聞きたいです．

**Comment by saitoeku3** [comment]
僕は Nuxt.js と Next.js のどちらも触るので、他の方の意見を尊重したいです。

今のところ @takanakahiko さんが Nuxt.js の方が習熟度が高いと仰っているので、Nuxt.js が良いのではないでしょうか。

**Comment by saitoeku3** [comment]
もし Nuxt.js を使うなら TypeScript でコンポーネントを書く方法を統一したいです。
(ちなみに僕は `Vue.extend` を使うことが多い)

**Comment by takanakahiko** [comment]
#20 で建てたので閉じます！
