### ISSUE TITLE
URI の設計

### ISSUE THREAD

**Issue by takanakahiko** [vlueprint/vlueprint#16]
rdf 内で定義する uri の命名規則を早めに決めたいなと思います

例えば im@sparql だと以下のような uri です
- https://sparql.crssnky.xyz/imasrdf/RDFs/detail/Himeno_Kanon
- https://sparql.crssnky.xyz/imasrdf/RDFs/detail/%E3%82%82%E3%81%B5%E3%82%82%E3%81%B5%E3%81%88%E3%82%93
- https://sparql.crssnky.xyz/imasrdf/RDFs/detail/Glory_Monochrome

また PrismDB だと以下のような uri です
- https://prismdb.takanakahiko.me/rdfs/character/manaka_laala
- https://prismdb.takanakahiko.me/rdfs/team/solami_smile
- https://prismdb.takanakahiko.me/rdfs/brand/twinkle_ribbon

ポイント
- クラスによってパスを切るか(例えば，キャラと同じ名前の曲とかがあっても困らない)
- uri に許容する文字は? ( 大文字はOK? 全角は? 記号は? )
- uri の命名規則は? (キャメルケース，パスカルケース，スネークケース，チェインケース)

**Comment by appachan** [comment]
## URIに許容する文字
これは一先ずTurtleの構文規則におけるIRI(URIのUnicodeへの拡張です)の勧告に従っておけばよいと思います．ほぼ無制限ですね．
>An IRI is a sequence of characters from the
   Universal Character Set (Unicode/ISO 10646). (https://www.ietf.org/rfc/rfc3987.txt)

気になるポイントがあるとすれば，URIで許されるようなASCII文字以外を使うと，キーボードで手打ちできなくなってクエリが書きにくくなる，とかでしょうか．

**Comment by takanakahiko** [comment]
例えばキズナアイの場合に

選択肢としては

- https://vluprint.org/rdf/キズナアイ
- https://vluprint.org/rdf/kizuna_ai

**Comment by takanakahiko** [comment]
> ## URIに許容する文字
> これは一先ず[Turtleの構文規則におけるIRI(URIのUnicodeへの拡張です)](https://www.w3.org/TR/turtle/#grammar-production-IRIREF)の勧告に従っておけばよいと思います．ほぼ無制限ですね．
> 
> > An IRI is a sequence of characters from the
> > Universal Character Set (Unicode/ISO 10646). (https://www.ietf.org/rfc/rfc3987.txt)
> 
> 気になるポイントがあるとすれば，URIで許されるようなASCII文字以外を使うと，キーボードで手打ちできなくなってクエリが書きにくくなる，とかでしょうか．

これは気にしなくて大丈夫だと思います．なぜなら，これを満たさない場合は rdflint で弾かれ， GtiHub Actions によるチェックで未然に防止できるからです．

**Comment by crssnky** [comment]
im@sparqlはここを参考にしています。(あくまで参考程度ですが)
-と_以外の記号は全てエンコードかけているつもりです。
http://www.asahi-net.or.jp/~ax2s-kmtn/ref/uric.html

**Comment by appachan** [comment]
ちなみに，Wikidataは`Q`もしくは`P`に任意桁の数字が続くIDを採用していますが，これは採用するべきでないと思います．ラベルなどを注釈表示するリッチなクエリUIが前提となるためです．

**Comment by appachan** [comment]
> 例えばキズナアイの場合に
> 
> 選択肢としては，パスのことを一回忘れると
> 
> * [https://vluprint.org/rdf/キズナアイ](https://vluprint.org/rdf/%E3%82%AD%E3%82%BA%E3%83%8A%E3%82%A2%E3%82%A4)
> * https://vluprint.org/rdf/kizuna_ai
> * https://vluprint.org/rdf/Kizuna_Ai
> * https://vluprint.org/rdf/KizunaAi
> 
> みたいな感じになりますね．

インスタンスのリソースURIについては，有名所だとDBpediaは下記のようなパスカルケースとアンダースコア，ハイフンによる区切りをミックスした記法を採用しています．上記キズナアイの例では，3番目に該当しそうです．

- 織田信長： http://dbpedia.org/resource/Oda_Nobunaga
- リュック・ベッソン： http://dbpedia.org/resource/Luc_Besson
- ジャン＝ジャック・ベネックス： http://dbpedia.org/resource/Jean-Jacques_Beineix

また，クラスによってインスタンスの名前空間を変更せず，下記のようにカッコ書きで注釈を設けます．

- http://dbpedia.org/resource/Jack_Collins_(actor)
- http://dbpedia.org/resource/Jack_Collins_(umpire)

運用に依る部分ではありそうですが，個人的には上記のように名前部分に注釈を付ける方がよいかなと思います．人物や楽曲といったコンテンツの種類（クラス）は無限にありますから，それにともなって名前空間の種類も増え，運用が煩雑になると考えられるからです．また，クラスの細分化といった変更がインスタンスのURIまで影響してしまう可能性があります．

**Comment by takanakahiko** [comment]
参考になりそうなものを貼っておきます 

http://data.e-stat.go.jp/lodw/en/outline/naming
https://www.w3.org/TR/ld-bp/#HTTP-URIS

**Comment by takanakahiko** [comment]
一つ，

> - http://dbpedia.org/resource/Jack_Collins_(actor)
> - http://dbpedia.org/resource/Jack_Collins_(umpire)

の形式で困ることは

キズナアイ(人物) :  https://vluprint.org/rdf/Kizuna_Ai
を作ったあとに
キズナアイ(曲) :  https://vluprint.org/rdf/Kizuna_Ai_(song)
が出た場合に
キズナアイ(人物) :  https://vluprint.org/rdf/Kizuna_Ai
を
キズナアイ(人物) :  https://vluprint.org/rdf/Kizuna_Ai_(virtual_being)
に変更しなければ行けないところでしょうか

**Comment by takanakahiko** [comment]
おもに [ここ](https://www.w3.org/TR/cooluris/) と dbpedia を見ていたんですが

- HTML を返すページと resouce uri は別にすべきなんですね...(今まで勘違いしてました)
- `/rdfs/${className}` と掘り下げる例はなさそうですね...
- 積極的にURIに日本語を採用している(それが許容されている)ようですね

そこで， 今回は以下のような構造にするのはどうでしょう

1. URIに日本語をバシバシ採用

- :+1: 英語表記を迷わなくていい
- :-1: URIとして取り回しが悪くなりそう

```
-  http://vlueprint.org/resource/キズナアイ のようにする
- 「キズナアイ」という曲が出たら
  - 「キズナアイ」という曲は http://vlueprint.org/resource/キズナアイ(曲) とする
  -  人物名は http://vlueprint.org/resource/キズナアイ のまま
```

2. URIは英語と記号のみとする

- :+1: 取り回しのしやすい URI となる
- :-1: 英語表記をしっかり調べる必要がある( 例えばシロちゃんは `shiro` じゃなくて `siro` )

```
-  http://vlueprint.org/resource/Kizuna_Ai のようにする
- 「キズナアイ」という曲が出たら
  - 「キズナアイ」という曲は http://vlueprint.org/resource/Kizuna_Ai_(song) とする
  -  人物名は http://vlueprint.org/resource/Kizuna_Ai のまま
```

**Comment by appachan** [comment]
> 一つ，
> 
> > * http://dbpedia.org/resource/Jack_Collins_(actor)
> > * http://dbpedia.org/resource/Jack_Collins_(umpire)
> 
> の形式で困ることは
> 
> キズナアイ(人物) : https://vluprint.org/rdf/Kizuna_Ai
> を作ったあとに
> キズナアイ(曲) : https://vluprint.org/rdf/Kizuna_Ai_(song)
> が出た場合に
> キズナアイ(人物) : https://vluprint.org/rdf/Kizuna_Ai
> を
> キズナアイ(人物) : https://vluprint.org/rdf/Kizuna_Ai_(virtual_being)
> に変更しなければ行けないところでしょうか

そうですね，その辺も議論が難しそうです．

ただし，新しく
キズナアイ(曲) : https://vluprint.org/rdf/Kizuna_Ai_(song)
が追加された後に，
キズナアイ(人物) : https://vluprint.org/rdf/Kizuna_Ai
を
キズナアイ(人物) : https://vluprint.org/rdf/Kizuna_Ai_(virtual_being)
に変更せずそのまま利用する，という運用でも正直よいかなという気はします．本質的にはURIは単なる識別子で意味をもたないからです（気持ち悪さは残る…）．あくまで異なるURIを割り当てるための注釈であって，ユーザ（検索する人やAPIを叩くシステム）は`<https://vluprint.org/rdf/Kizuna_Ai> a <https://vluprint.org/class/VirtualBeing> .`などの言明からキズナアイがVの者であることを解釈します．その文脈では，私の**注釈**という言い方もあまりよくないです．

これを極論するとWikidataのIDのような命名規則までいってしまうので程度問題かもしれませんが…

**Comment by takanakahiko** [comment]
> キズナアイ(人物) : https://vluprint.org/rdf/Kizuna_Ai_(virtual_being)
> に変更せずそのまま利用する，という運用でも正直よいかなという気はします．

私もこっちな気分になってきました．
例えば，Wikipediaやニコニコ大百科のような，皆でガツガツ編集するタイプのデータでは，元の記事のURLが変更されることは(ほとんど)ないからです．
また，今まで使われていたリンクが死んでしまうのも痛いですね．

**Comment by appachan** [comment]
>また，今まで使われていたリンクが死んでしまうのも痛いですしね．
正にこれで，クラスの細分化が名前空間の変更に影響する点もこれが一番シンドいです 👉

**Comment by takanakahiko** [comment]
あと DBpedia の `_` ですが，記事名の空白が `_` にリプレイスされているという法則があるみたいですね．
「`-` と `_` が混ざっている `Jean-Jacques_Beineix` 」も，ラベルは `Jean-Jacques Beineix` です．

**Comment by appachan** [comment]
おっしゃる通りだと思います．

ちなみにDBpediaはWikipedia（の特にInfobox）からRDFデータを自動抽出しています．以下参考です．
- http://www.semantic-web-journal.net/content/dbpedia-large-scale-multilingual-knowledge-base-extracted-wikipedia-0
- https://github.com/dbpedia/extraction-framework

**Comment by takanakahiko** [comment]
英語表記にする場合の表記決めの素案を考えました

前提

- 先頭は大文字とする
- 姓名等の区切りがある場合はスネークケース及びパスカルケースで区切る( exp: `Kizuna_Ai` )
- スペースは `_` にする

フロー

1. 公式の記述が見つかれば，それに従う
2. Wikipedia 等の記述が見つかればそれに従う
3. 以上2点が見つからない場合は **仮のURI** を作る
  - 英語で表記できそうな場合はその英語をそのまま
  - 英語で表記が難しい場合はローマ字変換する
  - それでも難しい場合は `str.normalize("NFKC").replace(/ /g,"").replace(/　/g,"")` する
  - 今後，正しい表記(公式からの表記)が見つかれば変更する

**Comment by appachan** [comment]
https://github.com/vlueprint/vlueprint/issues/16#issuecomment-597733548 こちらの「URIに日本語をバシバシ採用」の方ですが，日本語志向というよりかは，本来の名前の言語に準拠する（キズナアイならキズナアイ，[Melody](https://ja.wikipedia.org/wiki/Projekt_Melody)ならMelodyのように）方針とした方がいいかもしれないですね．

**Comment by takanakahiko** [comment]
あとは注釈についてですね．
これはどうしたものか．

## キズナアイという曲が発表された

1.  対応するオントロジーを探す( exp: https://vluprint.org/ontology/Song )
2. `_(${ontology})` を足す ( exp: `Kizuna_Ai_(Song)` )

## キズナアイというVtuberが(無いと思いますが)もうひとり出てきた(分身文脈はとりあえず置いておいて)

1.  一般的に差別化できる情報を探す( exp: ツイッターのIDが `kznai` なのでファンからは `kznai` 表記される )
2. `_(${差別化できる情報})` とする( exp: `Kizuna_Ai_(kznai)` )

**Comment by takanakahiko** [comment]
> [#16 (comment)](https://github.com/vlueprint/vlueprint/issues/16#issuecomment-597733548) こちらの「URIに日本語をバシバシ採用」の方ですが，日本語志向というよりかは，本来の名前の言語に準拠する（キズナアイならキズナアイ，[Melody](https://ja.wikipedia.org/wiki/Projekt_Melody)ならMelodyのように）方針とした方がいいかもしれないですね．

これはそのとおりだと思います

**Comment by takanakahiko** [comment]
英語のみor日本語許容，どちらにもメリットとデメリットがあることは理解した上で，じゃあどうするかとなると，完全に好みの問題ですよね．う〜〜〜ん．難しい．どっちも捨てがたい...．

**Comment by appachan** [comment]
https://github.com/vlueprint/vlueprint/issues/16#issuecomment-597754615
> ## キズナアイという曲が発表された
> 1. 対応するオントロジーを探す( exp: https://vluprint.org/ontology/Song )
> 2. `_(${ontology})` を足す ( exp: `Kizuna_Ai_(Song)` )

今回の要件ではこれで十分そうに思います 👍 

ちなみにDBpediaの http://dbpedia.org/ontology/ はクラスと一部のプロパティに対して割り当てられた名前空間なので，この場合 https://vluprint.org/ontology/Song は**クラス**でよいと思います． http://dbpedia.org/ontology/wtiter は主語の書籍・脚本などの著作家を指す属性， http://dbpedia.org/ontology/Wtiter は著作家のクラス，といったイメージです（個人的にこのススキーマの設計はイケてなさすぎると思っています…）．

> ## キズナアイというVtuberが(無いと思いますが)もうひとり出てきた(分身文脈はとりあえず置いておいて)
> 1. 一般的に差別化できる情報を探す( exp: ツイッターのIDが `kznai` なのでファンからは `kznai` 表記される )
> 2. `_(${差別化できる情報})` とする( exp: `Kizuna_Ai_(kznai)` )

こちらも賛成です．


https://github.com/vlueprint/vlueprint/issues/16#issuecomment-597762115
> 英語のみor日本語許容，どちらにもメリットとデメリットがあることは理解した上で，じゃあどうするかとなると，完全に好みの問題ですよね．う〜〜〜ん．難しい．どっちも捨てがたい...．

一般の編集者にとっては，**日本語許容**の方が少しだけ参加しやすいかも？と思います．コピペで良いですからね〜

**Comment by appachan** [comment]
>ちなみにDBpediaの http://dbpedia.org/ontology/ はクラスと一部のプロパティに対して割り当てられた名前空間なので，この場合 https://vluprint.org/ontology/Song はクラスでよいと思います． http://dbpedia.org/ontology/writer は主語の書籍・脚本などの著作家を指す属性， http://dbpedia.org/ontology/Writer は著作家のクラス，といったイメージです（個人的にこのススキーマの設計はイケてなさすぎると思っています…）．

これ，イケてないと思うのはtypoによって全く意味の異なるデータが生成されかねないためです．http://dbpedia.org/ontology/writer は http://dbpedia.org/property/writer ，http://dbpedia.org/ontology/Writer は http://dbpedia.org/class/writer とするか， http://dbpedia.org/ontology/writer ではなく http://dbpedia.org/ontology/hasWriter か http://dbpedia.org/ontology/writtenBy にする，もしくはその両方，あたりが代案として考えられます．

**Comment by takanakahiko** [comment]
調べたところ， `/class` のようなパスの振り方はあまりなかったので避けたいところですね...

- プロパティ : http://dbpedia.org/property/writer 
- クラス : http://dbpedia.org/class/writer

で良いと思いますが，どうでしょうか．

**Comment by takanakahiko** [comment]
ということで，とりあえず今の案をまとめ直します

## パスについて

- リソース : ` https://vluprint.org/resource/${key}`
- プロパティ : ` https://vluprint.org/property/${key}`
- クラス : ` https://vluprint.org/ontology/${key}`

## 命名規則について

- 正式名称(日本語含む)をそのまま key とする(この時点のものを `rdfs:label` とする)
- Unicode正規化 :  `key = key.normalize("NFKC")`
- 空白を `_` に変換 : `key = key.replace(/ /g,"_").replace(/　/g,"_")`
- 同一 key のリソースが出た場合
  - 対応するオントロジーを追加 :  `key = key + "_(" + ontology + ")"`
  - オントロジーも同じ場合は注釈を追加 :  `key = key + "_(" + annotation + ")"`

## ルール(提案)

- 1ヶ月程度は「URI は仮です」みたいな勧告をしたほうが良さそう
- クラス名はパスカルケース，プロパティ名はキャメルケース
- 注釈の意味等に関しては積極的に `rdfs:comment` で補足する

**Comment by takanakahiko** [comment]
```turtle
@base <https://vlueprint.org/resource/> .
@prefix vlueprint: <https://vlueprint.org/property/> .

@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

# プロパティ定義

vlueprint:youtubeChannel a rdf:Property;
    rdfs:label "YoutubeチャンネルID";
    rdfs:comment "チャンネルURLに関しては省略します";
    .

vlueprint:twitterAccount a rdf:Property;
    rdfs:label "Twitterアカウント";
    .

# クラス定義

vlueprint:VirtualBeing a rdfs:Class;
    rdfs:label "Virtual Being";
    rdfs:comment "一般的にVTuberとされる人物をこのクラスに当てはめます";
    .

# URI 

<キズナアイ> a vlueprint:VirtualBeing;
    rdfs:label "キズナアイ";
    rdfs:comment "Kizna Ai 表記と比較し，メジャーな キズナアイ 表記を採用しました";
    vlueprint:youtube "UC4YaOt1yT-ZeyB0OmxHgolA";
    vlueprint:youtube "UCbFwe3COkDrbNsbMyGNCsDg";
    vlueprint:twitterAccount "aichan_nel";
    .

<輝夜_月> a vlueprint:VirtualBeing;
    rdfs:label "輝夜 月";
    vlueprint:youtube "UCQYADFw7xEJ9oZSM5ZbqyBw";
    vlueprint:twitterAccount "_kaguyaluna";
    .

<電脳少女シロ> a vlueprint:VirtualBeing;
    rdfs:label "電脳少女シロ";
    vlueprint:youtube "UCLhUvJ_wO9hOvv_yYENu4fQ";
    vlueprint:twitterAccount "SIROyoutuber";
    .

<ミライアカリ> a vlueprint:VirtualBeing;
    rdfs:label "ミライアカリ";
    vlueprint:youtube "UCMYtONm441rBogWK_xPH9HA";
    vlueprint:twitterAccount "MiraiAkari_prj"
    .
```

**Comment by takanakahiko** [comment]
@appachan どうでしょうか...?

**Comment by appachan** [comment]
![LGTM](https://i.lgtm.fun/o3p.png)

**Comment by appachan** [comment]
https://github.com/vlueprint/vlueprint/issues/16#issuecomment-597785808 はお気持ちになってしまいましたが，私もプレフィクスが増えすぎるのは良くないと思い直しました．

また，SHACL良さそうですね 👍

**Comment by takanakahiko** [comment]
はい，ありがとうございます！(寿司LGTMいいですね)
