### ISSUE TITLE
GitHub Actions のバッジを README に追加したい

### ISSUE THREAD

**Issue by takanakahiko** [vlueprint/vlueprint#17]

**Comment by saitoeku3** [comment]
[Configuring a workflow - GitHub Help](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository) が参考になりそうですね！

**Comment by takanakahiko** [comment]
これは、だるいので誰かやってくれないかな〜というやつなので、よかったらどなたかお願いします

**Comment by appachan** [comment]
masterの先頭がすべてのworkflowを通過してると**passed**，一個でもコケてたらなら**failed**みたいなバッジを表示するやつですか？

**Comment by takanakahiko** [comment]
はい，そんなかんじです．

**Comment by takanakahiko** [comment]
これが参考になるかなと
https://github.com/takanakahiko/web-demo-suit/blob/master/README.md

**Comment by appachan** [comment]
`.github/workflows/rdflint.yaml`はp-r駆動なので，ひとまず`Delivery Containers`ワークフローのバッジを設置しておきました．

バッジはワークフロー単位でしか作れないんですね．

**Comment by takanakahiko** [comment]
ありがとうございました！
