### ISSUE TITLE
ペアとかグループのキャラがマージされてる

### ISSUE THREAD

**Issue by takanakahiko** [vlueprint/vlueprint#27]
例えば，ヒメヒナが１人としてカウントされてしまうのでどうにかしたい．
手でやっていくしか無いかな...?

https://github.com/vlueprint/vlueprint/blob/695b14d788b5ab646498eaa45a9a005d1e15febd/sparql-endpoint/toLoad/resource.turtle#L35

**Comment by takanakahiko** [comment]
今はこうなってる

```turtle
<https://vlueprint.org/resource/田中ヒメ_鈴木ヒナ> a vlueprint:VirtualBeing;
    rdfs:label "田中ヒメ 鈴木ヒナ";
    rdfs:comment "[TODO]チャンネルIDが取得できなかったので「vlueprint:youtubeChannelId」は指定されていません";
    vlueprint:youtubeChannelName "HIMEHINA Channel";
    vlueprint:twitterAccount "HimeTanaka_HH".
```

こうしたらよさそう

```turtle
<https://vlueprint.org/resource/田中ヒメ> a vlueprint:VirtualBeing;
    rdfs:label "田中ヒメ";
    vlueprint:twitterAccount "HimeTanaka_HH".

<https://vlueprint.org/resource/鈴木ヒナ> a vlueprint:VirtualBeing;
    rdfs:label "鈴木ヒナ";
    vlueprint:twitterAccount "HinaSuzuki_HH".

<https://vlueprint.org/resource/ヒメヒナ> a vlueprint:PerformingGroup;
    rdfs:label <https://vlueprint.org/resource/田中ヒメ_鈴木ヒナ>;
    rdfs:comment "[TODO]チャンネルIDが取得できなかったので「vlueprint:youtubeChannelId」は指定されていません";
    vlueprint:member <https://vlueprint.org/resource/田中ヒメ>;
    vlueprint:member <https://vlueprint.org/resource/鈴木ヒナ>;
    vlueprint:youtubeChannelName "HIMEHINA Channel";
```

**Comment by takanakahiko** [comment]
特に意見もなさそうなのでこれで進めましょうか．
PerformingGroup の定義に関しては別ファイルのほうが良さそうですかね...？

**Comment by appachan** [comment]
ファイル分割、単一のファイルに同時に複数の変更が提案されることを回避できて良さそうだと思います。

一方で、ヒメヒナ（各人）とヒメヒナ（グループ）を別ファイルにすると、両方編集したいときに面倒かも？という懸念も持ちました。

ですので、特別問題がなければ一先ずどちらでも良さそうという印象です。

**Comment by takanakahiko** [comment]
それだったら，一旦 `vlueprint:VirtualBeing` 用のファイルと `vlueprint:PerformingGroup` 用のファイルで分けたいですね〜．アレだったら後でガッチャンコしましょう．

**Comment by appachan** [comment]
賛成です🙋‍♀️

**Comment by nekketsuuu** [comment]
* 単に Group ではなく PerformingGroup としている理由はありますか？　わざわざ意味を狭める意図がいまいち分かりませんでした。
* vlueprint:VirtualBeing と vlueprint:PerformingGroup の間で N 対 N 関係になるので、#8 で議論されていたように vlueprint:VirtualBeing 側にも「所属」を示す関係が無くても大丈夫でしょうか？
    * https://github.com/vlueprint/vlueprint/issues/27#issuecomment-602228819 のやり方だと、たとえば「にじさんじ」にグループとしての YouTube チャンネルが[ある](https://www.youtube.com/channel/UCX7YkU9nEeaoZbkVLVajcMg)のを表現しようとしたとき、微妙にスキーマが揃わなさそうです。
* これは別の issue に分けるべきですが、vlueprint:youtubeChannelName はスキーマに含めなくて良いかもしれません（変更可能ですし、YouTube API から取得できるので）。

**Comment by takanakahiko** [comment]
> 単に Group ではなく PerformingGroup としている理由はありますか？　わざわざ意味を狭める意図がいまいち分かりませんでした。

Group  だけだと複数のもの全てに当てはまってしまうからです．
例えば複数の動画も Group と言えるでしょう．

命名に関しては，これは特に悩んでも仕方がないのと後で変えられるため，特に深く考えず [ここ](https://www.slideshare.net/secret/ICXnVi8gRRYwNA) に倣って PerformingGroup としました

> vlueprint:VirtualBeing と vlueprint:PerformingGroup の間で N 対 N 関係になるので、#8 で議論されていたように vlueprint:VirtualBeing 側にも「所属」を示す関係が無くても大丈夫でしょうか？

これに関して， rdflint にいわゆる逆参照を自動生成する機能があります．
`A -a-> B` なら `B -b-> A` とする，みたいなルールを定義できるのです．

今回ですと
- `<ヒメヒナ> vlueprint:member  <田中ヒメ>` だったら
- 自動的に `<田中ヒメ> vlueprint:memberOf  <ヒメヒナ>` となる
みたいな感じです

もちろん逆参照も Turtle ファイルで管理しても良いですが，冗長になってしまう気がします

> これは別の issue に分けるべきですが、vlueprint:youtubeChannelName はスキーマに含めなくて良いかもしれません（変更可能ですし、YouTube API から取得できるので）。

そうですね．別 Issue でお願いしたいです．
