### ISSUE TITLE
URI に紐づくWebページが欲しい

### ISSUE THREAD

**Issue by takanakahiko** [vlueprint/vlueprint#30]
PrismDB で言うところの https://prismdb.takanakahiko.me/rdfs/character/manaka_laala が必要かと思います．裏で SPARQL を叩いてプロパティ一覧を表示できればよいかと思います．

実装は [ここ](https://github.com/prickathon/prismdb/blob/master/web/pages/rdfs/_class/_key.vue) らへんが参考になるかと思います．

**Comment by takanakahiko** [comment]
https://vlueprint.org/resource/キズナアイ で キズナアイ に関する情報を一覧表示できると嬉しいです．

**Comment by appachan** [comment]
下記の方針に従って`https://vlueprint.org/(resource|schema)/*`を303でリダイレクトして上記のようなページを提供したいところですが、そうするとURLを検討する必要がありますね。
>There should be no confusion between identifiers for Web documents and identifiers for other resources. URIs are meant to identify only one of them, so one URI can't stand for both a Web document and a real-world object. ( https://www.w3.org/TR/cooluris/#semweb )

例えば、１段深堀りして`https://vlueprint.org/(resource|schema)/*`を`https://vlueprint.org/page/(resource|schema)/*`にするのが一案だと思います。resource/schemaを同じ名前空間に飛ばすと衝突する可能性があるのでマズそうですね。

参考に、DBpediaではインスタンスを表す`http:dbpedia.org/resource/*`は`http:dbpedia.org/page/*`にリダイレクトして、クラスやプロパティを表す`http:dbpedia.org/ontology/*`はそのまま200でwebページを表示しています。

**Comment by takanakahiko** [comment]
個人的には DBpedia のやつはアリかな〜と思っているんですけど，どうでしょうか？
それとも schema も resource も page に飛ばしちゃうとか

**Comment by appachan** [comment]
1. DBpediaのやつ、`resource`は303で`page`にリダイレクトして`schema`は200でそのまま表示ですね。思想的には、主のコンテンツが`resource/~`だからってことだと予想してるんですが、アリですね。
2. 一方shcema/resource両方`https://vlueprint.org/page/*`に飛ばすやつですが、クラスと同じ名前のvtuberやグループなどのインスタンスが発生したらコンフリクトするのでダメなのでは？と思います。

ひとまず1にしましょうか。
あとでWIPのp-r投げます。Nuxt.js初めて書いてて時間かかりそうなので、「俺がシュッとやるぜ」という人が他にいたら託していきたい。
