### ISSUE TITLE
ドメインを取りたい

### ISSUE THREAD

**Issue by takanakahiko** [vlueprint/vlueprint#5]
- 私が自腹してもいいけど，カンパがほしいところ
- ダメだった場合は `takanakahiko.me` のサブドメインになる

**Comment by uneco** [comment]
全額献金しますよー

**Comment by takanakahiko** [comment]
@uneco ありがとうございます！
お金を出してくれるひとは明確にしっかりとクレジットしたいので，適宜相談します．

プロダクト名が固まり次第，それを取りに行きます．

**Comment by takanakahiko** [comment]
#6 でプロダクト名が決まったので， `vlueprint.org` でとってきます！

**Comment by takanakahiko** [comment]
ひとまず建て替えておきます

![image](https://user-images.githubusercontent.com/10114717/76230647-5b3b7c00-6267-11ea-8114-c54fd5865a92.png)

**Comment by takanakahiko** [comment]
一応取るにはとったので閉じます

**Comment by takanakahiko** [comment]
https://vlueprint.org/
取得したドメインからのアクセスが可能になりました
