### ISSUE TITLE
プロダクト名を見直したい

### ISSUE THREAD

**Issue by takanakahiko** [vlueprint/vlueprint#6]
- `VtuberLOD` そのまま過ぎてダサい．(と，個人的に思う)
- また，明確に VTuber を対象とすると，VTuber であるかといった定義に踏み込まなければいけない( https://github.com/vtuber-lod/vtuber-lod/issues/3#issuecomment-596336315 )

**Comment by nekketsuuu** [comment]
「VTuber」という名前を採用すると他の人の VTuber の定義と照らし合わせながら考える必要が多少出てきて面倒というのは同意です。

一方で、名前を変えたところでその名前の範疇に入るかどうかは結局議論しなければいけません。そうしないと全人類をまとめることになり、ニコニコ大百科レベルの規模になってしまいます。

「バーチャル関係」や「Vの者」などの言葉で境界を曖昧にしつつ、明らかに異なるものは撥ねていくというのはひとつのやり方ですね。

**Comment by takanakahiko** [comment]
そうですね．「バーチャル」の文脈を残しつつ， VTuber を中心とした情報のハブとして，うまく機能させたいです．

**Comment by euxn23** [comment]
Virtual Being からとって Veing
https://namae.dev/s/veing

**Comment by euxn23** [comment]
https://namae.dev/s/virthday

**Comment by nekketsuuu** [comment]
FYI: Virtual Beings を略して Veing や Ving と言うのは既出です。

* https://twitter.com/robujera/status/1093172554955513856
* https://twitter.com/o_ob/status/1093338527780065280

**Comment by euxn23** [comment]
https://namae.dev/s/velief

**Comment by euxn23** [comment]
これめっちゃいいと思うんですがどうでしょう
https://namae.dev/s/vlueprint

**Comment by takanakahiko** [comment]
vlueprint かなりアリかなという気がしています．

**Comment by nekketsuuu** [comment]
nit: アメリカなどで使われている "Virtual Beings" という言葉は欧米的なアンドロイド感が含まれていて、具体的には今日本によくいる VTuber と異なり「魂がいない」感じの意味合いが強い（らしい）です。日本語だと「V の者」と「Virtual Beings」を同義として使っている方々もいらっしゃいますが……。

https://note.com/akton/n/n52d626efea8e

なお SIGGRAPH 2019 で開かれた ["Virtual Beings World"](https://s2019.siggraph.org/presentation/?id=bof_147&sess=sess385) というセッションでは下のように Virtual Beings を定義しているので、VTuber を包含します。ただこの定義がどこまで一般的なのか僕は詳しくないです。

> “Virtual Beings” - a new category of digital performers that include: "VTubers", Virtual Influencers, Digital Doubles, Virtual Idols and Avatar Societies

**Comment by takanakahiko** [comment]
その点について、特に欧米の方から指摘があれば、名前の由来の表記については見直しましょう。仮にダメだとしても、バーチャルだけにすれば良いと思うので、ここでは重要ではなさそうです。

しかし、こう言った点で配慮する必要があることを前もって知れたのは助かりました。情報ありがとうございます。

**Comment by takanakahiko** [comment]
ありがとうございます！
今日中に他の意見がなさそうだったらfixにしましょうか。

その際に、orgの名前とリポジトリ名を変更するので注意してください。

**Comment by takanakahiko** [comment]
fix!!!!!!!!!!!!!

**Comment by takanakahiko** [comment]
orgの名前とリポジトリ名を変更しました
