### ISSUE TITLE
インフラについて

### ISSUE THREAD

**Issue by takanakahiko** [vlueprint/vlueprint#7]
- お金はどうするか
- 構成はどうするか

**Comment by takanakahiko** [comment]
要件

- デプロイ前に csv2rdf したい
- SPARQL エンドポイント( Virtuoso というアプリケーション : [Docker Image](https://hub.docker.com/r/tenforce/virtuoso/) があります )
- URI に紐づくWebページをホストしたい(SSR)

**Comment by euxn23** [comment]
- CD / ビルド
  - GitHub Actions の枠が個人でも Pro 加入であればそこそこあるのでどうにかならないか
  - csv2rdf の結果をどこにホストするかによっては CloudBuild 等に逃がせないか
- Virtuoso
  - API 層とデータストア層が分離できるのであれば、 API 層を GAE/CloudRun が検討可能
  - s3fs のように起動時にマウントできるのであればそれでも良さそう
- SSR
  - GAE/CloudRun でも良さそう(最初期は無料枠で収まるのでは)

**Comment by euxn23** [comment]
金銭面についてはある程度出せます(project の backer という概念が存在すると良さそう)

**Comment by takanakahiko** [comment]
> * CD / ビルド
>   
>   * GitHub Actions の枠が個人でも Pro 加入であればそこそこあるのでどうにかならないか
>   * csv2rdf の結果をどこにホストするかによっては CloudBuild 等に逃がせないか
> * Virtuoso
>   
>   * API 層とデータストア層が分離できるのであれば、 API 層を GAE/CloudRun が検討可能
>   * s3fs のように起動時にマウントできるのであればそれでも良さそう
> * SSR
>   
>   * GAE/CloudRun でも良さそう(最初期は無料枠で収まるのでは)

ありがとうございます．

- `CD / ビルド` : GitHub Actions でやります．
- `Virtuoso` : CloudRun にします．データの更新がビルド時にしか発生しないので，永続化は不要なので，イメージのビルド時に rdf をねじ込む運用でどうにかします．
- `SSR`  : ですね，CloudRun にします．(無料枠超えたら考えます)

**Comment by takanakahiko** [comment]
スポンサーに付いていただいて、デプロイもできて、しっかり動いているので閉じます。
