### ISSUE TITLE
検索からの遷移が失敗する場合がある

### ISSUE THREAD

**Issue by takanakahiko** [vlueprint/vlueprint#81]
基本的に手元の開発環境だと発生しない。
リロードすると、正しく表示される。

![Jan-19-2021 12-55-53](https://user-images.githubusercontent.com/10114717/104986110-b6c4c180-5a55-11eb-8b32-65dbff4c19aa.gif)

**Comment by saitolume** [comment]
@takanakahiko  本番環境で同様のバグが確認できました！このバグの調査と修正に取り組んでみても良いですか？

**Comment by takanakahiko** [comment]
@saitolume よろしくお願いしたいです〜！

**Comment by saitolume** [comment]
@takanakahiko  本番環境で頻繁に動作確認しているときはエラーにならなかったので、Cloud Run (やコールドスタート) に問題があるのではないかと思い 2 つの原因候補を検討してみました。

## 候補 1: SSR 中のタイムアウトエラー

真っ先に思いつきましたが、gif 画像を見る限り時間がかかってそうではないので違いそうです。
念のため調査してみると「[axios にはデフォルトのタイムアウト時間が設定されていない](https://github.com/axios/axios/blob/master/README.md#request-config) (NuxtJS の Axios Module も同様)」「[`asyncData` の実行が終了するまでページ遷移をしない](https://ja.nuxtjs.org/docs/2.x/features/data-fetching/#async-data)」という理由で更にタイムアウトが原因だとは考えづらかったです。

## 候補 2: sparql-endpoint の RDF 読み取り遅延

実装からは API コールでエラーが発生したときと `SparqlResponse` に `bindings` が含まれないときに 404 エラーを返すことが読み取れます。今回の懸念は後者で、Cloud Run の API が実行されたときにまだ Cloud Run 側で RDF のデータを読み取れていなくて空のレスポンスを返してしまうのが問題ではないかと思いました。

https://github.com/vlueprint/vlueprint/blob/936a240a13ba13a590f35e594ee7df044314fb78/web/pages/_namespace/_key.vue#L30-L44

**Comment by takanakahiko** [comment]
おお、ありがとうございます！とても助かりました。
こちらでも再現しなくなってしまったので、どうしようかなといった次第です。

ちなみに

> Cloud Run の API が実行されたときにまだ Cloud Run 側で RDF のデータを読み取れていなくて

というのは考えづらくて、基本的に Docker Image のビルド時にデータの読み込み(というか流し込み)はすべて終わっているためです。
しかし `SparqlResponse` を返す API に何かしらの不具合があるという指摘は正しいと思います。（肌感）

暫定的な対処になりますが、 `Data not found` の部分が抽象的すぎるのでもう少しデバッグ可能な( 例えば catch 節 の表示を `e.toString()` にしてしまうなど )表示に変更するとかが無難かなと思いました。

**Comment by saitolume** [comment]
ネットワークエラーのログを確認できました `(failed)net::ERR_CONNECTION_REFUSED`

<img width="100%" alt="Screen Shot 2021-01-20 at 23 48 41" src="https://user-images.githubusercontent.com/38908416/105191165-1fa55a00-5b7a-11eb-9994-f874a66c1b45.png">

<img width="100%" alt="Screen Shot 2021-01-20 at 23 48 26" src="https://user-images.githubusercontent.com/38908416/105191191-259b3b00-5b7a-11eb-9087-416e0895b6c3.png">

**Comment by saitolume** [comment]
API の URL のドメイン部分が何故か localhost:3000 になっているので、これが原因だと思います

http://localhost:3000/sparql?query=SELECT+%3FProperty+%3FValue+WHERE+%7B+%3Chttps:%2F%2Fvlueprint.org%2Fresource%2F%E5%B0%8F%E6%9E%97%E5%B9%B8%E5%AD%90%3E+%3FProperty+%3FValue+%7D

**Comment by takanakahiko** [comment]
なるほど...！ありがとうございます
該当するリクエストを置き換えれば良さそうですね。

**Comment by takanakahiko** [comment]
`@nuxtjs/axios` と `@nuxtjs/proxy` のオプションに間違いがある気がして見直してる...。
しかし再現の条件がわからずに苦戦してます。

https://oisham.hatenablog.com/entry/2019/04/07/012231

**Comment by takanakahiko** [comment]
あーーーーーーーー、 `npm run build && PORT=8080 npm run start` (3000じゃないポート番号での開発環境立ち上げ)で再現しました。
結論から言うと、 `$axios.get` を用いてアクセスする場合の挙動がサーバサイド及びクライアントサイドで異なる動きをするということでした。

<details>
<summary>一応補足を書いておきますが、自分用（と、困った誰かの助けになりそうな）メモなので読まなくてもいいです。</summary>
---

前提として asyncData は、 URL 直叩きや `<a href="hoge" >huga</a>` での遷移ではサーバサイドで実行されますが、 `this.$router.push` や `<NuxtLink to="hoge">huga</NuxtLink>` での遷移ではクライアントサイドでその処理が実行されます。( asyncData 内に console.log とかを挟めばわかります )

次に `$axios` の仕様についてです。
`$axios` はサーバでの動作とクライアントでの動作を両方サポートしています。
また `axios` では BaseURL というオプションがあり、 `$axios` ではこれの自動設定をサポートしています。

また、これらの設定は環境変数によって決定されます。
本番環境の環境変数についてですが、クライアントコードは `npm run build`  時に読み込んだものを使い、サーバサイドはサーバの立ち上げ時に読み込んだものを使います。
これは、 Nuxt の Module の挙動です。

さらにもう一つ、CloudRun の挙動についてです。
CloudRun は Image が PORT という ENV を受け取ることを強制します。この PORT にサーバを立てる必要があります。
また、その値は実行時によって変化する可能性があり、ビルド時にはわからないのです。
よって、ビルド時には環境変数に 3000 ポートを指定するが、サーバ立ち上げ時には環境変数に 8080 ポートを指定される、なんてことが発生します。

で、`$axios` で自動設定される BaseURL オプションは [`http://$HOST:$PORT`](https://github.com/nuxt-community/axios-module/blob/a1a189486d63356433c939529d6e631f3fc9f923/lib/module.js#L61) になります。(例外あり)
よって、 なぜ `localhost:3000` を向いてしまうのか、といったことは明らかになりました。

ア〜〜〜〜〜〜〜〜〜〜〜スッキリした。
Nuxt の Module とか Plugin を勉強する良い機会になったのでヨシとしましょう。。

---</details>

つまりは、以下のように動作します。

```js
$axios.get( '/sparql', {
  params: { query }
})
//の挙動が

// クライアントサイドだと
const response = await axios.get('/sparql', {
  params: { query },
  baseURL: "https://localhost:3030" // ←いかんでしょ
})

// サーバサイドだと
const response = await axios.get('/sparql', {
  params: { query },
  baseURL: "https://localhost:8080"
})
```

これの対処方法ですが、 `nuxt.config.js` で [以下のようにすると良いことがわかりました。](https://github.com/nuxt-community/axios-module/blob/a1a189486d63356433c939529d6e631f3fc9f923/lib/module.js#L99)

```json
...
axios: {
  proxy: true,
},
...
```

これを入れることでクライアントサイドでの baseURL が変化して以下のようになるので解決すると思われます。


```js
$axios.get( '/sparql', {
  params: { query }
})
//の挙動が

// クライアントサイドだと
const response = await axios.get('/sparql', {
  params: { query },
  baseURL: "/" // ←最高や
})

// サーバサイドだと
const response = await axios.get('/sparql', {
  params: { query },
  baseURL: "https://localhost:8080"
})
```

<details>
<summary>一つ気がかりなのは、本番環境で再現しないタイミングがあったことです。</summary>


- 正しくレンダリングできた履歴からキャッシュを読みに行くことがある？（いやないやろ普通...）
- サーバ立ち上げてから一定時間が経過したらクライアントサイドのビルドを行い直すような処理が自動的に入る？（いやないやろ普通...）
- クライアントサイドでの asyncData が失敗したときにサーバサイドで実行し直す？（いやないやろ普通...）

うーん、わからんね...。
ま、直ればいいでしょ（適当）
</details>

**Comment by takanakahiko** [comment]
@saitolume さんが PR つくってくれたらマージしますし、面倒だったら僕やっちゃいます。
どちらでも良いのでおまかせします！

**Comment by saitolume** [comment]
@takanakahiko とても勉強になりました！引き継いで調査していただいてありがとうございます🙏

修正もやると言ったので PR 作りますね 
レビューよろしくお願いします🤲
